name: tahajjud_reminder
description: Basit Tahajjud namazı hatırlatıcı mobil uygulaması
version: 0.1.0+1
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  timezone: ^0.9.4
  geolocator: ^9.0.2
  http: ^0.13.6
  flutter_local_notifications: ^17.2.3

flutter:
  uses-material-design: true
